FROM nginx:alpine
COPY home /usr/share/nginx/html/home
COPY login /usr/share/nginx/html/login
COPY signup /usr/share/nginx/html/signup
COPY profile /usr/share/nginx/html/profile
COPY notes /usr/share/nginx/html/notes
COPY popular /usr/share/nginx/html/popular
COPY frontend/default.conf /etc/nginx/conf.d/default.conf